// apps/example-nuxt/app/components/Counter.vue
<script setup lang="ts">
import { ref } from "vue";
import { usePageObject } from "@ayme-dev/vue";
import { CounterPage } from "../../playwright/pom/CounterPage";

const count = ref(0);
const pom = usePageObject(CounterPage);
</script>

<template>
  <section aria-label="Counter">
    <p>
      Count: <output>{{ count }}</output>
    </p>
    <button @click="count += 1">Increment</button>
    <button @click="pom.increment()">Call Page Object</button>
  </section>
</template>

// apps/example-angular/src/app/counter.ts
import { Component, signal } from "@angular/core";
import { injectPageObject } from "@ayme-dev/angular";
import { CounterPage } from "../../playwright/pom/CounterPage";

@Component({
  selector: "app-counter",
  template: `
    <section aria-label="Counter">
      <p>
        Count: <output>{{ count() }}</output>
      </p>
      <button (click)="count.set(count() + 1)">Increment</button>
      <button (click)="pom.increment()">Call Page Object</button>
    </section>
  `,
})
export class Counter {
  protected readonly count = signal(0);
  protected readonly pom = injectPageObject(CounterPage);
}
