// packages/react/src/index.ts
import {
  createContext,
  createElement,
  useContext,
  useEffect,
  useId,
  useRef,
  useState,
  useSyncExternalStore,
  type ReactElement,
  type ReactNode,
} from "react";
import {
  createAyme,
  type Ayme,
  type AymeOptions,
  type AymeWebMcp,
} from "@ayme-dev/ayme";
import {
  markRenderSession,
  sameRuntimeOptions,
  type PageObjectConstructor,
} from "@ayme-dev/ayme/internal";

export type { AymeWebMcpPublicationStatus } from "@ayme-dev/ayme";
/** The options of `createAyme`, passed to it unchanged. */
export type AymeProviderProps = AymeOptions & { children?: ReactNode };
const RuntimeContext = createContext<Ayme | undefined>(undefined);

export function AymeProvider({
  children,
  ...options
}: AymeProviderProps): ReactElement {
  const ancestor = useContext(RuntimeContext);
  const [setup] = useState(() => {
    const snapshot = {
      ...options,
      webMCP: options.webMCP && { ...options.webMCP },
      inspector:
        typeof options.inspector === "object"
          ? { ...options.inspector }
          : options.inspector,
    };
    const runtime = createAyme(snapshot);
    // Without a window, React renders on the server, where the session must
    // never claim the process.
    if (typeof window === "undefined") markRenderSession(runtime);
    return { options: snapshot, runtime };
  });
  if (ancestor)
    throw new Error(
      "AymeProvider cannot be nested beneath another Ayme runtime owner."
    );
  if (!sameRuntimeOptions(options, setup.options))
    throw new Error(
      "The provider options must stay fixed while mounted. Remount the provider to change them."
    );
  useEffect(() => setup.runtime.start(), [setup]);
  return createElement(
    RuntimeContext.Provider,
    { value: setup.runtime },
    children
  );
}

function useRuntime() {
  const runtime = useContext(RuntimeContext);
  if (!runtime) throw new Error("Ayme hooks require an ancestor AymeProvider.");
  return runtime;
}

export type UseAymeResult = {
  /** The runtime session. */
  ayme: Ayme;
  /** The session's `webMCP` member, with its status as React state. */
  webMCP: Pick<AymeWebMcp, "publicationStatus" | "retryPublication">;
};

export function useAyme(): UseAymeResult {
  const runtime = useRuntime();
  const { webMCP } = runtime;
  const readStatus = () => webMCP.publicationStatus;
  const publicationStatus = useSyncExternalStore(
    webMCP.subscribe,
    readStatus,
    readStatus
  );
  return {
    ayme: runtime,
    webMCP: { publicationStatus, retryPublication: webMCP.retryPublication },
  };
}

export function usePageObject<T extends object>(
  model: PageObjectConstructor<T>
): T {
  const runtime = useRuntime();
  const [retained] = useState(() => ({ model, runtime }));
  if (retained.model !== model || retained.runtime !== runtime)
    throw new Error(
      "The Page Object model and provider must stay fixed while mounted. Remount the component to change them."
    );
  useEffect(() => {
    runtime.pom.register(model);
    return () => runtime.pom.unregister(model);
  }, [runtime, model]);
  return runtime.pom.get(model);
}

/**
 * Adds this component's instance of the Peek `name` while it is mounted,
 * through `ayme.peek`. The agent reads `values` from the latest committed
 * render. `id` defaults to one per mounted component.
 */
export function usePeek(values: unknown, name: string, id?: string): void {
  const runtime = useRuntime();
  const ownId = useId();
  const instanceId = id ?? ownId;
  const latest = useRef(values);
  // Before the registration effect, so the first read sees this render too.
  useEffect(() => {
    latest.current = values;
  });
  useEffect(
    () => runtime.peek(() => latest.current, name, instanceId),
    [runtime, name, instanceId]
  );
}

// packages/angular/src/index.ts
import {
  DestroyRef,
  InjectionToken,
  afterNextRender,
  assertInInjectionContext,
  inject,
  isSignal,
  makeEnvironmentProviders,
  provideEnvironmentInitializer,
  signal,
  type EnvironmentProviders,
  type Signal,
} from "@angular/core";
import {
  createAyme,
  type Ayme,
  type AymeOptions,
  type AymeWebMcpPublicationStatus,
} from "@ayme-dev/ayme";
import {
  markRenderSession,
  type PageObjectConstructor,
} from "@ayme-dev/ayme/internal";

export type { AymeOptions, AymeWebMcpPublicationStatus } from "@ayme-dev/ayme";

export type AymeWebMCP = {
  /** The session's publication status; `disabled` unless `webMCP.enabled`. */
  readonly publicationStatus: Signal<AymeWebMcpPublicationStatus>;
  retryPublication(): Promise<void>;
};

export type AymeSetup = {
  /** The runtime session. */
  readonly ayme: Ayme;
  readonly webMCP: AymeWebMCP;
};

// Stryker disable next-line StringLiteral: a debugging label Angular may print in injector errors; no behaviour reads it
const aymeSetup = new InjectionToken<AymeSetup>("Ayme setup");

/**
 * Starts Ayme with the environment injector that receives these providers,
 * before the root component is created, and stops it when that injector is
 * destroyed. Put it in the application config, not in route providers: the
 * router does not destroy a route's environment injector on navigation.
 */
export function provideAyme(options: AymeOptions = {}): EnvironmentProviders {
  return makeEnvironmentProviders([
    {
      provide: aymeSetup,
      useFactory: (): AymeSetup => {
        if (inject(aymeSetup, { skipSelf: true, optional: true }))
          throw new Error(
            "provideAyme cannot be nested beneath another Ayme runtime owner."
          );
        const ayme = createAyme(options);
        // Without a window, Angular renders on the server, where the session
        // must never claim the process.
        if (typeof window === "undefined") markRenderSession(ayme);
        const destroyRef = inject(DestroyRef);
        const publicationStatus = signal(ayme.webMCP.publicationStatus);
        destroyRef.onDestroy(
          ayme.webMCP.subscribe((status) => publicationStatus.set(status))
        );
        // A render session starts nothing.
        destroyRef.onDestroy(ayme.start());
        return {
          ayme,
          webMCP: {
            publicationStatus: publicationStatus.asReadonly(),
            retryPublication: ayme.webMCP.retryPublication,
          },
        };
      },
    },
    // Eager: the runtime starts with the environment, not on first injection.
    provideEnvironmentInitializer(() => void inject(aymeSetup)),
  ]);
}

/** Reads the Ayme setup of the nearest `provideAyme`. Call in an injection context. */
export function injectAyme(): AymeSetup {
  assertInInjectionContext(injectAyme);
  const setup = inject(aymeSetup, { optional: true });
  if (!setup)
    throw new Error("Ayme requires provideAyme() in an ancestor injector.");
  return setup;
}

/**
 * Returns the Page Object for the caller's lifetime: its tools are registered
 * until the caller's `DestroyRef` fires. Call in an injection context.
 */
export function injectPageObject<T extends object>(
  model: PageObjectConstructor<T>
): T {
  assertInInjectionContext(injectPageObject);
  const { ayme } = injectAyme();
  inject(DestroyRef).onDestroy(() => ayme.pom.unregister(model));
  return ayme.pom.register(model);
}

let instances = 0;

/**
 * Adds the caller's instance of the Peek `name` until its `DestroyRef` fires,
 * through `ayme.peek`. It is added after the first render, so never on the
 * server. The agent reads `values` when it asks, calling `values` if it is a
 * signal, or each top-level property that is one. `id` defaults to one per
 * caller. Call in an injection context.
 */
export function injectPeek(values: unknown, name: string, id?: string): void {
  assertInInjectionContext(injectPeek);
  const { ayme } = injectAyme();
  const instanceId = id ?? `ng-${++instances}`;
  let remove: (() => void) | undefined;
  inject(DestroyRef).onDestroy(() => remove?.());
  // Never runs during server rendering, and not after the caller is destroyed.
  afterNextRender(() => {
    remove = ayme.peek(() => readValues(values), name, instanceId);
  });
}

function readValues(values: unknown): unknown {
  if (isSignal(values)) return values();
  if (!isPlainObject(values)) return values;
  return Object.fromEntries(
    Object.entries(values).map(([key, value]) => [
      key,
      isSignal(value) ? value() : value,
    ])
  );
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  if (typeof value !== "object" || value === null) return false;
  const prototype = Object.getPrototypeOf(value) as unknown;
  return prototype === Object.prototype || prototype === null;
}
