// apps/example-sveltekit/src/lib/Counter.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { useAyme, usePageObject } from "@ayme-dev/svelte";
  import { CounterPage } from "$lib/pom/CounterPage";
  import { SubCounterPage } from "$lib/pom/SubCounterPage";

  const { ayme } = useAyme();
  const pom = usePageObject(CounterPage);
  usePageObject(SubCounterPage);
  let count = $state(0);
  let runtimeAtMount = $state("pending");

  // A stopped runtime lists no tools, so a list shows the runtime had
  // started before this component mounted.
  onMount(() => {
    runtimeAtMount = ayme.tools.list().length > 0 ? "started" : "stopped";
  });
</script>

<section aria-label="Counter">
  <p>Count: <output>{count}</output></p>
  <button onclick={() => (count += 1)}>Increment</button>
  <button onclick={() => pom.increment()}>Call Page Object</button>
  <p data-testid="started">Runtime at child mount: {runtimeAtMount}</p>
</section>

// apps/example-nuxt/app/components/Counter.vue
<script setup lang="ts">
import { ref } from "vue";
import { usePageObject } from "@ayme-dev/vue";
import { CounterPage } from "../../playwright/pom/CounterPage";
import { SubCounterPage } from "../../playwright/pom/SubCounterPage";

const count = ref(0);
const pom = usePageObject(CounterPage);
usePageObject(SubCounterPage);
</script>

<template>
  <section aria-label="Counter">
    <p>
      Count: <output>{{ count }}</output>
    </p>
    <button @click="count += 1">Increment</button>
    <button @click="pom.increment()">Call Page Object</button>
  </section>
</template>
